### PR TITLE
Add vanity hash to README

### PR DESCRIPTION
**Pull request by gforsyth**

### CODE REVIEW

**Review by saulpw — COMMENTED** [review]
Please add ~10 newlines/spaces at the end before running vainhash (it replaces the last N characters).

**Comment by gforsyth** [comment]
Done.

**Comment by gforsyth** [comment]
I'll come back to this tomorrow

**Comment by saulpw** [comment]
Yeah, I may need to update this utility to take a set of valid characters so that it can be ASCII only.

**Pull request closed without merging**
